### ISSUE TITLE
list of to dos

### ISSUE THREAD

**Issue by paulinetrinh** [statdivlab/happi#12]
- multiple starts 
- take in formula for lambda ~ X
- take in formula for f ~ M
- inc. plot() method to show fitted f(.)
- arbitrary p = ncol of X
- arbitrary q = ncol of M
- standard errors on beta's

**Comment by adw96** [comment]
@paulinetrinh are these all separate issues now? If so, can we close? 🙏

**Comment by paulinetrinh** [comment]
yup! will close
