### ISSUE TITLE
multiple starts

### ISSUE THREAD

**Issue by paulinetrinh** [statdivlab/happi#27]
check that multiple starts implementation results in sensible results

**Comment by adw96** [comment]
So this exists but doesn’t work? If so, can we add a warning if someone puts in nstarts>2? (As a temporary fix)

**Comment by paulinetrinh** [comment]
yes! this exists. It needs more checking that it results in sensible output and is behaving as we want it to!

**Comment by svteichman** [comment]
This exists and behaves as expected (when multiple starts are used, the start with the highest log likelihood is used for both the null and alternative model). I suggest closing this issue.

**Comment by paulinetrinh** [comment]
Yay! Thanks Sarah for checking it.
