### ISSUE TITLE
Using Checkm output for genome quality info (+FDR question)

### ISSUE THREAD

**Issue by Somebodyatthdoor** [statdivlab/happi#50]
Hi,

I was wondering if it was possible to use genome completeness (as output by tools such as CheckM), rather than coverage for the genome quality info? I feel it is a more accurate measurement of genome quality than coverage, particularly now Checkm2 has been released. 

I was also unsure from the documentation whether it is possible to run comparisons for all of the genes provided in your dataset, not just one at a time? And if so, whether FDR can be calculated as part of happi, or whether this needs to be done post hoc. 

Thanks for your help,
Laura

**Comment by adw96** [comment]
Hi Laura! Great questions! 

Absolutely you can use genome completeness from checkM as the quality info! I agree that in many situations (especially in relatively better-studied human microbiome settings) that completeness >> coverage. (Less well in CPR genomes like the TM7's we looked at in the paper )

Absolutely yes you can run comparisons for all genes. @paulinetrinh Can you confirm that we don't have an example of how to run `happi` with multiple genes and performing FDR control? This is definitely something we should do. @paulinetrinh what's your interest/bandwidth for adding this in? I can ask Sarah and Maria if none. 

Thanks for your interest in happi, Laura! We appreciate your feedback and constructive questions and requests! More soon.

**Comment by adw96** [comment]
Also, @Somebodyatthdoor, please do send us your suggestions for how to make happi easier to use and better documented. This is something we'll prioritize in proportion to the level of community interest! 📈

**Comment by paulinetrinh** [comment]
@adw96 it doesn't look like there's an example on how to run it on multiple genes and do the fdr correction in the vignette (I'm embarrassed that I missed including that!). I can add it but wouldn't be able to get to it until another week and a half or two at the earliest (hopefully it's not urgently needed sooner than that).

**Comment by Somebodyatthdoor** [comment]
@paulinetrinh That would be great if you have the time. There isn't an urgent rush.

My plan is to use the tool not only to look at individual genes, but gene families and predicted metabolic pathways (as output by MicrobeAnnotator). From my understanding of how the tool works I imagine that would be fine?

**Comment by adw96** [comment]
That sounds totally reasonable, @Somebodyatthdoor . 

@paulinetrinh If you can give this a go starting in a couple of weeks that would be great! Happy to advise as you go. I'd recommend BY over BH as it does better under positive dependence (easy to do with `p.adjust(p_values, method="BY")`). 

I've put a note on my calendar to check in if I haven't heard from you @paulinetrinh -- thank you!

And huge thanks to @Somebodyatthdoor for the constructive suggestions.

**Comment by paulinetrinh** [comment]
Just FYI @Somebodyatthdoor that this is on my calendar for next week and once things are finalized I'll ping you to let you know it's available! Coming soon.

**Comment by adw96** [comment]
I think this is fully addressed, but feel free to reopen if I'm mistaken @Somebodyatthdoor
