### ISSUE TITLE
Error in x$loglik : $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by Somebodyatthdoor** [statdivlab/happi#54]
Hi,

I am currently trying to run the npLRT() function on multiple genes, as described in the newer version of the vignette. I am having a bit of trouble extracting values from the resulting output, getting a " x$loglik : $ operator is invalid for atomic vectors". This doesn't seem to happen when I run the standard happi command without npLRT.

Code:

Sig_IBV_Pos_par_dbcan2 <- Sig_IBV_metadata_dbcan2 %>% 
  select(IBV_Pos, Completeness, `GH001`:ncol(.)) %>%
  mutate(IBV_Pos_bin = ifelse(IBV_Pos == "IBV_Pos", 1, 0)) %>% 
  select(2, ncol(.), 3:(ncol(.) - 1))  # clean up data to only contain the gene presence/absence matrix, the genome quality variable, and the primary covariate of interest 

x_matrix_Sig_IBV_Pos_par_dbcan <-  model.matrix(~IBV_Pos_bin, data = Sig_IBV_Pos_par_dbcan2)

run_happi_IBV_Pos_dbcan <- function(column) {
  happi_results_dbcan_IBV_Pos <- happi(outcome=unlist(Sig_IBV_Pos_par_dbcan2[,column]), # specify columns of Sig_IBV_par_dbcan2 dataset
                                       # input your covariate matrix object here
                                       covariate=x_matrix_Sig_IBV_Pos_par_dbcan, 
                                       # specify your genome quality variable here
                                       quality_var=Sig_IBV_Pos_par_dbcan2$Completeness, 
                                       # choose your method for estimating f, default splines                 
                                       method="splines", 
                                       # use firth's penalty = TRUE        
                                       firth=T,
                                       # if using method = splines specify number of splines, default 3
                                       spline_df=4, 
                                       # the maximum number of EM steps that the algorithm will run for
                                       max_iterations=1000, 
                                       # change threshold of the likelihood for algorithm to stop at 
                                       change_threshold=0.1, 
                                       # probability of observing a gene when it should be absent
                                       epsilon=0) 
  
  npLRT_results_dbcan_IBV_Pos <- happi::npLRT(happi_results_dbcan_IBV_Pos, 
                                method="splines", 
                                firth=T, 
                                spline_df=4,
                                max_iterations=1000, 
                                change_threshold=0.1, 
                                epsilon=0, 
                                P = 1000)
  
  return(npLRT_results_dbcan_IBV_Pos)
}

set.seed(8)
DBcan_IBV_Pos_results <- mclapply(3:148, run_happi_IBV_Pos_dbcan, mc.cores=16) # 3:148 denotes the dbcan columns I want to run that exist in columns 3 - 148. run_run_happi_IBV_Pos_dbcan is the function we created above and mc.cores allows you to specify how many cores you want to allocate to this computational task 

pvalue_DBcan_IBV_Pos <-  lapply(DBcan_IBV_Pos_results, function(x) tail(x$loglik$pvalue_nopenalty[!is.na(x$loglik$pvalue_nopenalty)], 1)) %>% unlist

This is when the error occurs. I imagine this is due to the output changing format between happi() and npLRT()?

Cheers,
Laura

**Comment by adw96** [comment]
Thanks so much for letting us know, @Somebodyatthdoor ! I'm travelling for the next couple of weeks so I will leave you in the capable hands of @svteichman . Sarah, thanks so much for debugging this one 🙏

**Comment by svteichman** [comment]
Hi @Somebodyatthdoor, thanks for letting us know about this. While the `happi` function outputs an entire list with a lot of information, including a `loglik` table with a `pvalue_nopenalty` column that gives the p-values, the `npLRT` function returns a single value, which is the p-value. What does your list `DBcan_IBV_Pos_results` look like? My guess it that it may be a list of your non-parametric permutation test p-values. If you run `DBcan_IBV_Pos_results %>% unlist()`, which happens? Do you get a vector of p-values? Let me know if this works, if what the output is if it doesn't.

**Comment by Somebodyatthdoor** [comment]
Hi @svteichman,

Yup, that outputs a vector of p-values.  And are those p-values definitely in the same order as the inputted genes? If so then I can see how to go ahead with my analysis. 

It might be useful to add a very short description for processing the  npLRT_results (up to FDR correction) in the vignette. Just so that it is clear that you need to process these results slightly different for the standard happi command.

Thanks for all your help,
Laura

**Comment by svteichman** [comment]
Hi @Somebodyatthdoor, 

Yes, your p-values from the `npLRT` function are in the order of the arguments that you gave to the function `run_happi_IBV_Pos_dbcan` that you wrote. It looks like you are inputting `3:148` as the sequence of arguments, so once you unlist the p-value results, they will be in the order corresponding to columns 3-148 of your `Sig_IBV_Pos_par_dbcan2` data frame. 

Thanks for your suggestion, we're still actively working on the documentation for these functions and it's very helpful to hear what could be better for users! I'm going to close this issue because it seems like it is resolved for now, but feel free to re-open if needed. 

For @svteichman and @adw96, we should address issue #39, update the output of the main `happi` function to make it easier to work with, and update the vignette "happi-intro.Rmd" to reflect this.
