### ISSUE TITLE
Try to run happi message error variable names are limited to 10000 bytes

### ISSUE THREAD

**Issue by auroregaltier99** [statdivlab/happi#56]
Hello, I am trying to run happi on my panaroo matrix absence/presence table using a matatable containing oral_site binary column and completeness of my assembly column. When running it in a snakemake command like this: 
        Rscript {input.script} \
        --input {input.data} \
        --metadata {input.metadata} \
        --output {output} \
        --quality_var {params.quality_var} \
        --covariate {params.covariate} \
        --epsilon {params.epsilon} \
        --minit {params.min_iterations} \
        --maxit {params.max_iterations} \
        --method {params.method} \
        --firth {params.firth} \
        --spline_df {params.spline_df} \
        --perm {params.perm} \
        --num_perm {params.num_perm} \
        --nstarts {params.nstarts} \
        --seed {params.seed} \
        --change_threshold {params.change_threshold} \
        --cores {params.cores}
        """
I get this error message: 
Error in `dplyr::arrange()`:
! Problem with the implicit `transmute()` step.
Caused by error in `initialize()`:
! variable names are limited to 10000 bytes
Backtrace:
     ▆
  1. ├─my_gene_presence %>% dplyr::arrange(ID)
  2. ├─dplyr::arrange(., ID)
  3. ├─dplyr:::arrange.data.frame(., ID)
  4. │ └─dplyr:::arrange_rows(.data, dots)
  5. │   ├─base::withCallingHandlers(...)
  6. │   ├─dplyr::transmute(new_data_frame(.data), !!!quosures)
  7. │   └─dplyr:::transmute.data.frame(new_data_frame(.data), !!!quosures)
  8. │     └─dplyr:::mutate_cols(.data, dots, caller_env = caller_env())
  9. │       └─DataMask$new(.data, caller_env, "mutate", error_call = error_call)
 10. │         └─dplyr (local) initialize(...)
 11. └─base::.handleSimpleError(...)
 12.   └─dplyr (local) h(simpleError(msg, call))
 13.     └─rlang::abort(bullets, call = error_call, parent = parent)
Execution halted

Could you help to understand what is the issue?

**Comment by adw96** [comment]
Hi @auroregaltier99 ! Unfortunately this is out of scope for us. If you're able to come up with a minimal example of applying happi to a single gene, we can help with that -- but debugging a snakemake pipeline isn't something we can offer. Thanks for understanding and I look forward to helping you with your MWE.
